#ifndef DEF_ZULAMAN_H
#define DEF_ZULAMAN_H

#define DATA_NALORAKKEVENT  1
#define DATA_AKILZONEVENT   2
#define DATA_JANALAIEVENT   3
#define DATA_HALAZZIEVENT   4
#define DATA_HEXLORDEVENT   5
#define DATA_DAAKARAEVENT   6
#define DATA_CHESTLOOTED    7
#define DATA_ZULJINEVENT    8
#define TYPE_RAND_VENDOR_1  9
#define TYPE_RAND_VENDOR_2  10

#endif

